### ISSUE TITLE
Check for static type hints and `declare(strict_types=1);`

### ISSUE THREAD

**Issue by tmotyl** [extdn/github-actions-m2#1]
It would be nice if the PHP_CodeSniffer  actions are extended to check for static type hints and whether `declare(strict_types=1);` is missing.
e.g. using https://github.com/slevomat/coding-standard
https://github.com/slevomat/coding-standard#slevomatcodingstandardtypehintsdeclarestricttypes-

**Comment by fooman** [comment]
@tmotyl Thanks for your suggestion. This action is using the upstream Magento Coding Standard. I suggest following this issue here https://github.com/magento/magento-coding-standard/issues/33 - once available it will be utilised by this github action as well.
