### ISSUE TITLE
[Question] Run Magento Coding Standard check on changed files

### ISSUE THREAD

**Issue by tuyennn** [extdn/github-actions-m2#106]
Hi, folks
I'm currently got an idea to run the `extdn/github-actions-m2/magento-coding-standard` on changed list files, example in a pull request.

Any help would be appreciated.

**Comment by sprankhub** [comment]
That was pretty much implemented here: https://github.com/mage-os/github-actions/tree/main/coding-standard-baseline
And is used here: https://github.com/mage-os/mageos-magento2/blob/2.4-develop/.github/workflows/coding-standard-baseline.yml

This can give you an idea. However, these actions are currently still very much targeted to `mage-os/mageos-magento2` - I am not sure if you can run those on your code base.

If you do not have a huge code base, the `phpcs` check should run fast anyway, though?

**Comment by tuyennn** [comment]
@sprankhub happy to see your quick reply.
Indeed this is detail https://github.com/mage-os/github-actions/blob/main/coding-standard-baseline/action.yml
Just invest some experiments on my personal projects, and they are not so big.
