### ISSUE TITLE
Add php copy paste detector action

### ISSUE THREAD

**Issue by sqlexception** [extdn/github-actions-m2#2]
it would be awesome to add [phpcpd](https://github.com/sebastianbergmann/phpcpd)

**Comment by fooman** [comment]
@sqlexception thanks for the suggestion. Looking at https://github.com/magento/magento2/blob/2.4-develop/dev/tests/static/testsuite/Magento/Test/Php/LiveCodeTest.php#L374 I don't believe we would need a separate action to https://github.com/marketplace/actions/php-copy-paste-detector. 

The only thing Magento specific is the blacklist for core files which would not be needed outside of core development.

I'll close this one for the moment but if someone wants to contribute happy to merge it. I would suggest taking a look at the mess-detector action as a starting point.
