### ISSUE TITLE
Add problem matcher support for PHPMD

### ISSUE THREAD

**Issue by DmitryFurs** [extdn/github-actions-m2#45]
In the coding-standard action, support for problem matcher has been added, and when creating a pull request, all the problems found are highlighted when viewing the execution result, as well as when viewing the pull request itself. The found problems that were not affected by the new changes are also displayed.

![image](https://user-images.githubusercontent.com/1055999/143547839-ded877c7-a262-48e3-91ed-7c2798e481e7.png)

![image](https://user-images.githubusercontent.com/1055999/143547861-0cabe07f-c210-41a6-8a4e-4a75eb9bf989.png)

![image](https://user-images.githubusercontent.com/1055999/143547848-0a0e5d96-1a55-4017-a903-6318fb87a9c3.png)

But when viewing the result of the execution of PHPMD, we can only see the result of the execution by opening the logs. This is inconvenient, since you need to copy the filepath and search for the desired string.

![image](https://user-images.githubusercontent.com/1055999/143547943-ea2b9e50-7ab2-47f4-b633-aba1be95afa9.png)

![image](https://user-images.githubusercontent.com/1055999/143547960-891bf3ad-3b7f-42f5-8ee7-c091d89327ef.png)

Judging by the PHPMD documentation they have an implemented renderer supported by github
https://phpmd.org/documentation/index.html#renderers
https://phpmd.org/documentation/ci-integration.html#github-actions

Judging by the code, the `text` renderer is currently being used, and if it is replaced with "`github`, then everything should work automatically.
https://github.com/extdn/github-actions-m2/blob/master/magento-mess-detector/LiveCodePhpmdRunner.php#L62

If it doesn't work, then most likely we need to implement an additional problem matcher to support PHPMD, as it is done for Coding Standard https://github.com/extdn/github-actions-m2/blob/master/magento-coding-standard/problem-matcher.json

**Comment by DmitryFurs** [comment]
@sprankhub thanks! feel free to contribute :)

**Comment by sprankhub** [comment]
Oh, I did not want to steal that simple fix after your perfect analysis, but sure: #46. Not sure how we can test this properly, though :thinking:
