### ISSUE TITLE
Monolog 2.7 causes breaking changes that make Integration Tests fail

### ISSUE THREAD

**Issue by jissereitsma** [extdn/github-actions-m2#72]
In my environment, Magento 2.4.4 with PHP 8.1 causes the installation of Monolog 2.7, which again has changed method signatures that are used by the Magento TestFramework to log stuff. This issue is reported at Magento here: https://github.com/magento/magento2/issues/35720

The workaround is to add `composer require monolog/monolog:2.6.0` somewhere to the Integration Tests, right before doing a `composer install`. I've personally added it to a pre-install script.

Anyone else bumping into this? If so, I might simply add it to the GitHub Action here instead.

**Comment by damienwebdev** [comment]
@jissereitsma indeed - https://github.com/graycoreio/github-actions-magento2/blob/main/.github/workflows/integration.yaml#L114

This came from @convenient https://github.com/magento/magento2/pull/35596

**Comment by jissereitsma** [comment]
Note that 2.8 will still include this change :)

My own Magento issue is a duplicate. I'll close it right away.

**Comment by jissereitsma** [comment]
Added for now like this: https://github.com/extdn/github-actions-m2/commit/1cc6ce6b38f772c70b6cbc41f2a108bed5069709

**Comment by convenient** [comment]
@jissereitsma Yeah agreed that 2.8 monolog will still include this change my thoughts were

- Do not use 2.7.0 as its known breaking
- Wait for feedback on https://github.com/Seldaek/monolog/issues/1684 and https://github.com/magento/magento2/pull/35596 to see what the "correct" thing to do is
    - Hope that either of those projects will fix forward and bring compatibility back in again

This was to hopefully prevent against weird scenarios in future where I've locked to 2.6.0 but need higher, honestly as well to keep it painful a little bit. Don't want to forget this is an issue that needs handled :p

**Comment by jissereitsma** [comment]
@convenient I definitely like the approach of asking for feedback on the comment that Jordi (Seldaek) made, but I'm actually not sure if anyone will pick up on this. It might very well be that the person know built this in the past, moved on already.

A handler is a better idea indeed. I already refactored a couple of things in my dev environment to allow for this. But I'm also just wondering who is using this logging ability. Plus I read that in PHPUnit 10 the logger listening feature is actually going to be removed :o
