### ISSUE TITLE
Integration tests failing for Magento 2.3

### ISSUE THREAD

**Issue by Vinod-MultiSafepay** [extdn/github-actions-m2#90]
When running integration tests for Magento 2.3 with PHP 7.3, it fails because in commit https://github.com/extdn/github-actions-m2/pull/87 a change has been introduced that adds a flag during setup which is not available in Magento 2.3.

```
Run Magento setup: --base-url=http://magento2.test/ --db-host=mysql --db-name=magento2 --db-user=root --db-*** --admin-firstname=John --admin-lastname=Doe --admin-email=johndoe@example.com --admin-user=johndoe --admin-*** --backend-frontname=admin --language=en_US --currency=USD --timezone=Europe/Amsterdam --sales-order-increment-prefix=ORD_ --session-save=db --use-rewrites=1 --search-engine=elasticsearch7

                                                
  The "--search-engine" option does not exist.  
```

**Comment by sprankhub** [comment]
Thanks for reporting. Options I could think of:

1. Ignore the issue, because 2.3 is EOL.
2. Tag a major new version with the change, so that people could use an older version of the actions if they still want to have 2.3 support.
3. Only add the new flag for newer Magento versions.

I tend to go with version 2. What do you think, @jissereitsma? What are your thoughts, @Vinod-MultiSafepay?

**Comment by Vinod-MultiSafepay** [comment]
Hi @sprankhub ,

Creating a tag for the latest version where 2.3 still works does not really help, since the docker image that is being used is still the latest one with the last updated entrypoint shell script. We would have to create our own docker images if we would go that route. It would be almost the same as ignoring the issue here, since we already have a fork of this repository with changes in it.

Checking the version before adding the flag would be the best solution for us, since that wouldn't require creating a separate docker image.

@jissereitsma I'm curious about your opinion.

**Comment by sprankhub** [comment]
@Vinod-MultiSafepay, could you check if https://github.com/extdn/github-actions-m2/pull/91 works for you?

**Comment by Vinod-MultiSafepay** [comment]
@sprankhub ,

Thanks for the PR, it's working great!
